### ISSUE TITLE
Arena detection

### ISSUE THREAD

**Issue by MagicMicky** [MrRobotoIRT/Jacques#3]
When the user's click on the Detect Arena button from the monitor, we should start the detection of the arena.
- [x] On Start arena signal from monitor, start the aperiodic thread `thread_gerer_arene`
- [x] If signal is `ACTION_FIND_ARENA` Ask for the detection of the arena from the supervisor, and stop the image sending
- [x] If signal is `ACTION_ARENA_IS_FOUND` save the arena, and restart the image sending
- [x] If signal is `ACTION_ARENA_CANCELED` set arena to NULL and restart the image sending

**Comment by realsoc** [comment]
Pioupiou
